### ISSUE TITLE
Pop_sum and spatial join for nightlights.csv

### ISSUE THREAD

**Issue by GIS243** [thinkingmachines/ph-poverty-mapping#32]
Hi @ardieorden ardieorden

How you are getting the pop_sum in the nightlights file. and while performing a spatial join using (1) the layer with the longitude and latitude and (2) the buffered layer with the DHS clusters.

are you using one to one or one to many spatial join?

Thanks

**Comment by ardieorden** [comment]
Hi @GIS243 , thanks for showing interest in our work!

Getting `pop_sum` requires the HRSL data as well as `nightlights.csv`. Just like the VIIRS data, the [HRSL data](https://www.ciesin.columbia.edu/data/hrsl/) is also in an image format. 

Recall that `nightlights.csv` has:
- longitude
- latitude
- nighttime light intensity

In order to get `pop_sum`, you need to:
1. Open `nightlights.csv` in QGIS.
2. Open the HRSL data in QGIS.
3. Go to `Plugins > Analyses > Point Sampling Tool` and use `nightlights.csv` layer as "Layer containing sampling points" and then and Band 1 of the HRSL data as "Layers with fields/bands to get values from". Go to the "Fields" tab and rename Band 1 as `pop_sum`. Go back to the "General" tab and save the "Output point vector layer" as a CSV.

Now, this should give something similar to `nightlights.csv`.

**Comment by GIS243** [comment]
Hi @ardieorden 

Thanks for the reply. 

I have another question regarding the DHS data file **PHHR70DT/PHHR70FL.DTA** mentioned in the code. As this  dataset has one record for each household.  So there are many **education completed in single years** variables. Which particular variable you are taking , are you taking the average of the varialbes.


Thanks

**Comment by ardieorden** [comment]
Hi @GIS243 , I saw your message in my inbox and I'd like to share it here so that other people can benefit as well.

> Hi @ardieorden
> 
> Thanks for the reply.
> 
> I have another question regarding the DHS data file PHHR70DT/PHHR70FL.DTA mentioned in the code. As this dataset has one record for each household. So there are many education completed in single years variables. Which particular variable you are taking , are you taking the average of the varialbes.

As far as I remember, we took the "education completed" variables per household for all households.

**Comment by jtmiclat** [comment]
Hi! Closing this issue as ill be archiving this repository. To see our new poverty mapping project checkout https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping
