### ISSUE TITLE
boundaries CSV files

### ISSUE THREAD

**Issue by sabman** [thinkingmachines/ph-poverty-mapping#34]
Quick question. I am trying to reproduce the work and while running the [03_transfer_model.ipynb](https://github.com/thinkingmachines/ph-poverty-mapping/blob/master/notebooks/03_transfer_model.ipynb)

It is expecting the following files which seem to be missing:

```py
dhs_provinces_file = data_dir+'dhs_provinces.csv'
dhs_regions_file = data_dir+'dhs_regions.csv'
```

I don't see where they were created. Should they have been generated in the preparation? If so It could be that the original DHS data mentioned in the `00_dhs_prep.ipynb` (`PHHR70DT/PHHR70FL.DTA`, `PHHR70DT/PHHR70FL.DO`) isn't available instead I was able to find these :

```py
dhs_file = dhs_zip + 'PHHR71DT/PHHR71FL.DTA'
dhs_dict_file = dhs_zip + 'PHHR71DT/PHHR71FL.DO'
```
Any pointers would be greatly appreciated! Thanks again for publishing your work and merry christmas! 🎄 🎅

**Comment by Skerre** [comment]
Dear Sabman,

I am having the same issue. 
Did anyone answer you with a solution?

Best,
Martin

**Comment by ardieorden** [comment]
Hi @sabman , apologies for the late reply!

The `dhs_regions.csv` file was uploaded a few weeks ago. You can check it out here: https://github.com/thinkingmachines/ph-poverty-mapping/blob/master/data/dhs_regions.csv.

`dhs_provinces.csv` and `dhs_regions.csv` were _not_ generated in the Jupyter Notebooks and were actually created using QGIS.

I will just ask @ibtingzon if she still has a copy of `dhs_provinces.csv` so that she can upload it to the repo.

**Comment by ardieorden** [comment]
@sabman In the meantime, I think you can remove the following variables:
- `dhs_provinces_file` 
- `dhs_provinces`
- `province_cols`

**Comment by sabman** [comment]
Thanks @ardieorden trying it out today appreciate your taking the time to get back to me. 🙇
