### ISSUE TITLE
dhs_regions

### ISSUE THREAD

**Issue by GIS243** [thinkingmachines/ph-poverty-mapping#39]
Hi 

I hope you are doing well. 

Can you please let me know how you are getting the dhs_regions.csv file? 

Thanks

**Comment by ardieorden** [comment]
Hi @GIS243 , the `dhs_regions.csv` file was created using one hot encoding. The categorical variables (i.e. region name) were converted into a numerical data that was either 1 or 0.

**Comment by GIS243** [comment]
Thanks 

can you please share a code for this thanks

**Comment by ardieorden** [comment]
Hi @GIS243 , I'm not sure if our code for doing this is currently available in the repo.

But here are some code samples that you might be able to use:
- https://machinelearningmastery.com/how-to-one-hot-encode-sequence-data-in-python/
- https://www.geeksforgeeks.org/ml-one-hot-encoding-of-datasets-in-python/

**Comment by RizwanZa** [comment]
Hi

I hope you are doing well.

Can you please send me dhs_indicators.csv file or .DTA and .DO?

**Comment by ardieorden** [comment]
Hi @RizwanZa ,

Unfortunately, [due to data access agreements](https://superset.unicef.io/), we cannot send the `.dta` and `.do` files.

You would have to download data these files yourselves from the DHS Program website ([instructions](https://dhsprogram.com/data/Access-Instructions.cfm)) and then you can create the `dhs_indiators.csv` file by running the `/notebooks/00_dhs_prep.ipynb` Jupyter notebook.

**Comment by jtmiclat** [comment]
Hi! Closing this issue as ill be archiving this repository. To see our new poverty mapping project checkout https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping
